### ISSUE TITLE
TTGO SPI

### ISSUE THREAD

**Issue by IhorNehrutsa** [peterhinch/micropython-nano-gui#11]
https://github.com/peterhinch/micropython-nano-gui/blob/090509a4d9920369a0017f4647d480acf652c969/color_setup/st7789_ttgo.py#L73-L74

The screen is black if the baud rate grater than 33Mhz.
Is it a hardware limit?

ssd._spi.deinit() is required at the end of demos examples.

**Comment by peterhinch** [comment]
I had varied experiences with baudrates above 30MHz. In one test it worked fine at 60MHz, but next time I tried the display was corrupted.

This is an electrical issue, as detailed in the docs. To run reliably at high frequencies you need a PCB with a groundplane and short interconnects. This is a normal issue of electronics design, and not a problem with the hardware or the driver.
