### ISSUE TITLE
Ref README.md - photographing  OLED display images

### ISSUE THREAD

**Issue by PaulskPt** [peterhinch/micropython-nano-gui#30]
Hi Peter, I just read the contents of README.md from this repo because I want to try to use this repo.
In this README.md you wrote: ``` OLEDs are visually impressive displays with bright colors, wide
viewing angle and extreme contrast.  For some reason I find them hard to photograph. ```.

I am not a photographer. Regularly I take photographs of hardware setups and of images on displays. Usually, to be quick, I use my iPhone to take photographs. My experience using this mobile phone to take photographs of displays is not overwhelmingly positive. I also own a ```Canon PowerShot G7X Mk II``` camera. With that camera I have much better success in making photographs of displays. The Canon Camera can deal better with the big brilliance of the OLED displays because you can set diaphragma, shutter time etc. The camera of the mobile phone is more  automatic controlled thus more limited in adjustments by the user; in this case resulting in blurry characters (as shown below) and in other occasions showing artifacts too.

Below a comparison: image 1 taken with an iPhon8Plus; image 2 taken with the Canon PowerShot mentioned above.

Image 1:
![IMG_3488](https://user-images.githubusercontent.com/9107950/148286329-eaf5dc81-81ef-43f6-ae81-0d325add14c8.jpg)

Technical details of image 1:

![IMG_3488_info](https://user-images.githubusercontent.com/9107950/148287625-c61bd1ca-8cb7-4ee4-94e2-3800e5f50c2c.png)

Image 2. I did not take too much time adjusting settings of the Canon camera. I am sure that if I did, the quality of the image would be even better.

![2022-01-03_23h18_](https://user-images.githubusercontent.com/9107950/148286259-0e67bed3-7cf7-4ecc-a853-857438147abc.JPG)

Technical details of image 2:

![2022-01-03_23h18_info](https://user-images.githubusercontent.com/9107950/148288071-91f395ca-bdd5-4b32-a8b8-2e79b7d146dc.png)

**Comment by peterhinch** [comment]
I have recently learned a bit about photographing displays. The trick is to put everything in manual mode, shutter speed, aperture and focus. Clamp everything securely and avoid very short exposures. Here is an example.

![Image](https://github.com/peterhinch/micropython-monitor/raw/master/images/la_ui.jpg)

**Comment by PaulskPt** [comment]
Excellent!

**Comment by peterhinch** [comment]
A couple of points I missed. Ensure a minimum amount of ambient light: I photograph in evening, but you could devise some kind of shade. Secondly, if colors are washed-out, there is local overexposure: reduce aperture.

Good luck!
