### ISSUE TITLE
The dial class and pointers

### ISSUE THREAD

**Issue by beetlegigg** [peterhinch/micropython-nano-gui#37]
Thanks for the excellent library, I like it a lot.  Must admit my heart sank with the dial widget when I saw it used complex numbers which I did not have a clue what they were and initial googles did not enlighten me.  I expect complex numbers are well understood by real programmers and engineers, but for this old boy hobby dabbler I've never come across them before.

However I came across mathsisfun.com which did put me on the right path, at least as far as its used for the dial pointer class.  I don't really get the imaginary number stuff but I have worked out that the dial has 2 ranges - a horizontal one that goes from -x to +x (left to right) and a vertical one that goes from  +y to -y (top to bottom).  Both these ranges meet in the middle at 0x and 0y.

These ranges can be addresses in python with the built in function 'complex(x,y), for the horizontal and vertical axis.   So for a compass bearing of North at the top (0 degrees) one can put complex(0,90)  (no horizontal jut a vertical going up).  Other bearings follow this pattern so 90 degrees is complex(90,0) (horizontal to the right and no vertical).  180 degrees is complex(0,-90) (no horizontal but vertical going down thus a minus).  The bearings in-between are extrapolated so a bearing of 230 degrees would be complex(-50,-40) (horizontal to the left so a '-' and vertical going down so another '-'

I give this explanation for any, who like me, have not a clue about these complex numbers and as the words probably don't adequately explain it I give my small demo program (amateur python programming) to illustrate. 

I create a  function 'position_calc(..) that has arguments for the pointer to use, the number of segments in the circle desired (so 360 for a compass or 60 for an hours worth of minutes etc) and a position to display  (e.g 270 for 270 degrees of a 360 degree circle or 15 for 15 minutes of a circle representing an hour of 60 minutes circle.

Its probably not very well written, and there must be a more elegant way (but don't mention complicated maths :-) ).  I found it easier to do the maths with the positive and negative complex numbers to think of the circle as divided into 4 quadrants, so the first bit of the program calculates the quartile the desired bearing is in and then does the simple maths, just addition or subtraction no use is made of more complicated maths from the cmath library :-)

Program Code Starts:
from color_setup import ssd  # Create a display instance
from gui.core.colors import *
from gui.core.nanogui import refresh
from time import sleep

import gui.fonts.freesans20 as freesans20
from gui.core.writer import CWriter
from gui.widgets.dial import Dial, Pointer

CWriter.set_textpos(ssd, 0, 0)  # In case previous tests have altered it
wri = CWriter(ssd, freesans20, GREEN, BLACK, verbose=False)
refresh(ssd, True)  # Initialise and clear display.

dial = Dial(wri, 60, 40, height = 120, ticks = 8,
            label = '     Bearing', style = Dial.CLOCK, pip=CYAN,
            fgcolor = CYAN)
dial.show()

pointer = Pointer(dial)

def position_calc(pointer, segments, position):
    if position > segments:
        print('position value greater than segments')
        return
    if (segments % 4) != 0:
        print('segments must be divisible by 4 without any left over')
        return
    q_segments = segments / 4
    if position <= q_segments:
        quartile = 1
    elif position > q_segments and position <= q_segments *2:
        quartile = 2
        position = position - q_segments
    elif position > q_segments *2 and position <= q_segments *3:
        quartile = 3
        position = position - q_segments *2
    else:
        quartile = 4
        position = position - q_segments *3
          
    if quartile == 1: # 0, q_segments
        Horizontal = 0 + position
        Vertical = q_segments - position
        pointer.value(complex(Horizontal, Vertical), MAGENTA)
    elif quartile == 2: # q_segments, 0
        Horizontal = q_segments - position
        Vertical = 0 - position
        pointer.value(complex(Horizontal, Vertical), RED)
    elif quartile == 3: # 0, -q_segments
        Horizontal =  0 - position
        Vertical = (q_segments *-1) + position
        pointer.value(complex(Horizontal, Vertical), CYAN)
    elif quartile == 4: # -q_segments, 0
        Horizontal =  (q_segments *-1) + position
        Vertical = 0 + position
        pointer.value(complex(Horizontal, Vertical), GREEN)

    print('H:',Horizontal, ' V:',Vertical)

segments = 360
bearing = 230

position_calc(pointer, segments, bearing)
refresh(ssd)

"""
# for 60 minutes (so 60 segments)
# start at 1 and wiz round to 60 with 0.25 intervals
segments = 60
for seg in range(1, segments+1):
    position_calc(pointer, segments, seg)
    refresh(ssd)
    sleep(0.25)

"""
Code Ends

OK all the above is probably only of use to a mathematically challenged old boy so feel free to junk this post.

But I have another motivation for this post and that was to see if you have any tips for creating a bigger arrow pointer.   I'm using the ili9341 screen with a rpi pico.  I cannot really see the arrow head and it rather merges with a 'tick' mark when the compass pointer stops at the tick point.  (the demo code I presented uses the CLOCK rather than the COMPASS as its not so clear which end is which as the arrow head is rather indistinct.) 

Also, the docs mention a pointer method of text(),  but the code in the dial.py widget does not appear to have any such method.  (I was a good boy and actually read the docs!)

I'm trying to set up a dial to show the current wind direction, but also to show the direction as text.  I can use the label class just as well for this, so if its not intended for the pointer to have a text() method then its not really an issue.

Again, many thanks for a really useful library.

**Comment by peterhinch** [comment]
Thank you for pointing out the error in the docs: there is no label associated with the `Pointer` class. I will delete this cut-and-paste error.

Re the chevron length, this is defined [here](https://github.com/peterhinch/micropython-nano-gui/blob/2b26eee39630cb6a05ef3859169ba98bb7c6f7d6/gui/widgets/dial.py#L103). Increase the number 5 (in pixels) to your taste. This will affect both head and tail of the arrow.

Re complex numbers these represent quantities that have magnitude and direction (like wind speed and bearing). These quantities (called vectors) can be represented as X and Y values, but such representation has drawbacks. Firstly it is not intuitive. If you're on top of a mountain in a howling gale it's not helpful to be told that the wind is 70mph northerly and 40mph easterly. You want a speed and bearing. Secondly, if you have a vector represented as conventional X and Y magnitudes and you want to rotate it by 30 degrees using that coordinate system you get involved in horrible trigonometry.

Complex numbers can be represented either in rectangular (X and Y) or polar (mag and direction) form. If I create a complex number to represent that wind (70 + 40j) and I want to rotate it by 30 degrees I create another number `r = rect(1, π*30/180)`. Rotating the wind vector is simply a matter of multiplying by `r`.

It is well worth getting to grips with complex numbers if you want to handle vectors or do circular graphics.

**Comment by peterhinch** [comment]
You might like to look at the `arrow` function in `dial.py`. It draws an arrow of any length and any angle with only basic arithmetic operators. With only real numbers it would be a sea of `sin`, `cos` and `tan` functions.

Good luck with your learning :+1:
