### ISSUE TITLE
Add support for LilyGo T-display S3

### ISSUE THREAD

**Issue by hemna** [peterhinch/micropython-nano-gui#41]
LilyGo has added ST7789 support for their parallel display on the T-Display S3 here:

https://github.com/Xinyuan-LilyGO/lilygo-micropython/issues/16

Any chance someone can write a driver for this for nano-gui ?

Here is an example for drawing to the display:
https://github.com/liangyingy/st7789_binding_micropython/blob/master/examples/framebuf/use_framebuf.py

**Comment by hemna** [comment]
https://github.com/peterhinch/micropython-nano-gui/pull/42

**Comment by peterhinch** [comment]
Closed due to inactivity.
