### ISSUE TITLE
No align= in Label widget

### ISSUE THREAD

**Issue by beetlegigg** [peterhinch/micropython-nano-gui#44]
As per the docs - option 9 of the Label class has an the ability to do align=ALIGN_CENTER,  but this does not work and a peruse of the Label class  shows its not there.  Is this a doc error or has it be left out of the code by mistake?
Thanks

**Comment by peterhinch** [comment]
This worked in testing. This [line](https://github.com/peterhinch/micropython-nano-gui/blob/7eb050b03eb08603ca039ee1846fee7a4f736f85/gui/widgets/label.py#L54) is only executed if it is not left aligned, so the `else` clause only runs if it is centre aligned. That is why there is no explicit reference to `ALIGN_CENTER`. Centre alignment occurs for any value that is not in `{0, 1}`.

If you are not seeing centre alignment the most likely reason is that the width of the `Label` instance is too small to allow it.

**Comment by peterhinch** [comment]
It was a very recent enhancement.
