### ISSUE TITLE
ssd.wait (for class EPD) does not exist

### ISSUE THREAD

**Issue by ZedOud** [peterhinch/micropython-nano-gui#66]
I was looking at the two async EPD demos:

- epd_async.py
- epd29_async.py

and both make use of a `ssd.wait()`
However, my linter, as well as manually browsing through ...
`from color_setup import ssd`
v
`ssd = SSD()`
v
`from drivers.epaper.pico_epaper_42 import EPD as SSD`
v
`class EPD(framebuf.FrameBuffer):`
v
`class FrameBuffer:`
... confirms that there is no property of `.wait` in that line of inheritance.

**Comment by peterhinch** [comment]
Thank you for the report. The scripts should wait on the `ssd.complete` and `ssd.upated` events. I have pushed an update.
