### ISSUE TITLE
Issues with the SSD1339 driver

### ISSUE THREAD

**Issue by vvlang** [peterhinch/micropython-nano-gui#67]
I have an SSD1339 OLED display, and although the driver I wrote (ssd1339.py) can display content, the image shown when running the test program is skewed. Could you please tell me what the issue might be?

[ssd1339.py](https://raw.githubusercontent.com/vvlang/ssd1339/main/ssd1339.py)  
[test.py](https://raw.githubusercontent.com/vvlang/ssd1339/main/test.py)  

MicroPython v1.22.2, pico v1.22.2 on 2024-03-06; Raspberry Pi Pico with RP2040

![IMG_8671](https://github.com/peterhinch/micropython-nano-gui/assets/45045804/6aab1692-b6e4-42d1-be45-296675f243aa)

**Comment by vvlang** [comment]
[https://raw.githubusercontent.com/vvlang/ssd1339/main/ssd1339.py](url)ssd1339.py
[https://raw.githubusercontent.com/vvlang/ssd1339/main/test.py](url) test.py

**Comment by peterhinch** [comment]
It's not really possible for me to debug a driver for hardware which I don't possess. The display you're seeing is typical of the sort of thing you get with a faulty driver. The only way to sort this out is to study the chip datasheet and be sure that every line of code makes sense in that context. Writing display drivers is quite time consuming. Good luck.
