### ISSUE TITLE
esp8266 memory error

### ISSUE THREAD

**Issue by eugeniobaglieri** [peterhinch/micropython-nano-gui#7]
Good evening, i'm triyng to use nano-gui on esp8266 with SSSD1331 display.
I'm importing (not using frozen modules) the minimum .py files structure as suggested in README.
I can instatiate the ssd object, but when i try to create a Label object i get memory error.
Has something changed from that written in the README?
Does Importing library as frozen module resolve the issue?

**Comment by peterhinch** [comment]
The ESP8266 has limited RAM, and I was quite surprised that nano-gui could be made to run on it. The [instructions](https://github.com/peterhinch/micropython-nano-gui/blob/master/README.md#4-esp8266) make it clear that it is necessary to use frozen bytecode on the ESP8266.
